### ISSUE TITLE
Update DS Homestead to more up-to-date version with official Laravel Homestead

### ISSUE THREAD

**Issue by weerd** [DoSomething/ds-homestead#18]
We might want to consider upgrading our Homestead to fall more in line w/ the current official [Laravel Homestead repository](https://github.com/laravel/homestead).

It would be ideal if there could be some way to keep up to date with official Homestead on a more regular basis while still using additional scripts to add additional items, like MongoDB.

Thoughts?

**Comment by DFurnes** [comment]
It looks like official Homestead [may include MongoDB](https://github.com/laravel/homestead/blob/master/scripts/install-mongo.sh) now? 😲

**Comment by weerd** [comment]
Oh shiza! Nice... so maybe that answers that, haha. 

So, second part, ideally Homestead is at par with whatever our QA/Prod env are so that Dev/QA/Prod are more closely matched...

**Comment by DFurnes** [comment]
Yeah, we still have potential dev/prod version mismatches since we're usually a little bit less quick to adopt the newest version of Ubuntu, PHP, and MongoDB than Taylor is. That may be less of an issue in practice since we always test our code through CI and QA servers?

I'm definitely in favor of reducing the number of things we have to manage ourselves.

**Comment by weerd** [comment]
True. I just wasn't sure how big of a concern it was to be closer, since yeah, Taylor is a fan of upgrading often ;)

**Comment by pnasrat** [comment]
I think we can think longer term about the second goal of having consistent environments from development to production.

**Comment by pnasrat** [comment]
cc @blisteringherb

**Comment by DFurnes** [comment]
I did a little playing around with this and it seems to work really nicely! There's an [undocumented `mongodb:true` flag in `Homestead.yaml`](https://git.io/vDJjY) that adds MongoDB support.

I tested it out on Northstar and ran into a tiny issue because the mcrypt extension was not available (DoSomething/northstar#568), but otherwise things seem to work perfectly! It would probably be good to do a quick audit and see if there are any other major differences between this box and our production environments so we don't have too many other surprises.

**Comment by DFurnes** [comment]
We've made that update in Northstar, so should be good if anyone else wants to give this a try!

**Comment by weerd** [comment]
I'll probs give it a whirl soooon and report back!

**Comment by DFurnes** [comment]
Closing & archiving this repo since we're using stock Homestead now.
