### ISSUE TITLE
update php version

### ISSUE THREAD

**Issue by angaither** [DoSomething/ds-homestead#8]
it seems the newer version of homestead uses php7, not php7 and when running vagrant up, it gives `php5-fpm unrecognized service`

**Comment by DFurnes** [comment]
Are we planning on using PHP 7 in production? If not, it might make sense to version lock to an [older Homestead box](https://atlas.hashicorp.com/laravel/boxes/homestead) with 5.6 instead.

**Comment by angaither** [comment]
a fair point from the man, the legend @DFurnes 
either way. the box doesn't work when you run `vagrant up` because it's expecting a different version of php than what's running.

**Comment by sheyd** [comment]
We actually have an active DevOps ticket out for PHP 7 to replace PHP 5.
Only thing that really preventing a test is if Phoenix will work with it,
since everything else is in Laravel's, and the compatibility there is
pretty solid. @DFurnes, any thoughts or bugs you've run into with PHP7 not
working with Laravel?

**Comment by DFurnes** [comment]
Ahh, exciting! :tada: I haven't tested anything with PHP 7 yet. It [looks like Laravel MongoDB support](https://github.com/jenssegers/laravel-mongodb/releases/tag/v3.0.0-alpha) may still not be fully ready though so it could be good to wait a little bit.

**Comment by DFurnes** [comment]
Closing this since we're now on PHP 7! 🔨
